Layout added
Atikingi/SkyFitnessPro pull request #21
Opened 2022-12-08 13:20 UTC by lokkib

2022-12-08 13:54 UTC, Atikingi requested changes

2022-12-08 13:54 UTC, Atikingi commented on src/layouts/style.module.css
> +  margin-left: 140px;
У меня дома стоит 2К монитор. Представляешь как растянется сайт. Давай тогда просто назначим по макету ширину контента и просто отцентрируем его

2022-12-08 13:54 UTC, Atikingi commented on package-lock.json
> +    "node_modules/typescript": {
нам вроде не нужен TS в проекте

2022-12-09 11:28 UTC, 17u5h approved these changes

2022-12-09 11:31 UTC, 17u5h commented on src/App.jsx
> +      </Routes>
по хорошему тут добавить бы <Route path='*' element{<NotFound/>}/>

А также писать роуты не в App.js, а в routes.js

2022-12-09 11:40 UTC, lokkib commented on src/layouts/style.module.css
> +  margin-left: 140px;
отцентрировал процентами пока

2022-12-09 11:40 UTC, lokkib commented on package-lock.json
> +    "node_modules/typescript": {
++

2022-12-09 11:41 UTC, lokkib commented on src/layouts/Layout.jsx
> +    <div className={styles.container}>
Посмотри тогда завтра еще, но логика работает, я проверил

2022-12-09 11:42 UTC, lokkib commented on src/App.jsx
> +      </Routes>
роуты в папке сделал, а насчет path=* - ты тогда можешь сделать, если считаешь нужным действительно, я пока в целом оставил место для роутов тебе)

2022-12-09 11:48 UTC, 17u5h approved these changes

2022-12-09 11:54 UTC, 17u5h commented on src/App.jsx
> +      </Routes>
отлично!

2022-12-09 12:54 UTC, Atikingi approved these changes
Approve!

2022-12-09 12:55 UTC, merged